# Generated by Django 4.1.7 on 2023-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(max_length=50),
        ),
    ]
