# Generated by Django 4.1.7 on 2023-05-10 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=255)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coach')),
                ('students', models.ManyToManyField(related_name='group_students', to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_count', models.IntegerField()),
                ('attendance', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coach')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='author',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='author',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='salary_per_hour',
        ),
        migrations.AddField(
            model_name='administrator',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='coach',
            name='groupqs',
            field=models.ManyToManyField(related_name='coach_groupqs', to='myapp.group'),
        ),
        migrations.AddField(
            model_name='coach',
            name='students',
            field=models.ManyToManyField(to='myapp.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='group_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
    ]
