# Generated by Django 4.1.7 on 2023-05-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client_coach_group_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='groupqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='coach_groupqs', to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.client'),
        ),
    ]
