# Generated by Django 5.0.3 on 2024-03-20 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
