# Generated by Django 5.0.3 on 2024-03-20 07:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_administrator_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='last_active',
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.administrator')),
            ],
        ),
    ]
