# Generated by Django 5.0.3 on 2024-03-20 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_administrator_last_active_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
