# Generated by Django 5.0.3 on 2024-03-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_administrator_last_active_delete_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
