# Generated by Django 5.0.3 on 2024-03-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
