# Generated by Django 5.0.3 on 2024-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_markedattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='button_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
