# Generated by Django 5.0.3 on 2024-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subscription_button_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='card_number',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
