# Generated by Django 5.0.3 on 2024-03-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_client_address_client_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='myapp.subscription'),
        ),
    ]
