# Generated by Django 5.0.3 on 2024-03-23 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
