# Generated by Django 5.0.3 on 2024-03-23 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_subscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='start_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
