# Generated by Django 5.0.3 on 2024-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_useractivitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='start_time',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
