# Generated by Django 5.0.3 on 2024-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_useractivitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='end_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='start_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
