# Generated by Django 5.0.3 on 2024-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_useractivitylog_end_time_useractivitylog_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
