# Generated by Django 5.0.3 on 2024-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_useractivitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
