# Generated by Django 5.0.3 on 2024-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_coach_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='groupqs',
            field=models.ManyToManyField(blank=True, related_name='coach_groupqs', to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='students',
            field=models.ManyToManyField(blank=True, to='myapp.client'),
        ),
    ]
