# Generated by Django 5.0.3 on 2024-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_coach_groupqs_alter_coach_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
