# Generated by Django 5.0.3 on 2024-03-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_markedattendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='groupqs',
            field=models.ManyToManyField(related_name='coach_groupqs', to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='students',
            field=models.ManyToManyField(related_name='coach_students', to='myapp.client'),
        ),
        migrations.AlterField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_groups', to='myapp.coach'),
        ),
        migrations.AlterField(
            model_name='markedattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
