# Generated by Django 5.0.3 on 2024-03-24 10:35

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(default=myapp.models.default_datetime),
        ),
    ]
