# Generated by Django 5.0.3 on 2024-03-24 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_useractivitylog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_datetime_field', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
