# Generated by Django 5.0.3 on 2024-03-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_subscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('num_lessons', models.PositiveIntegerField()),
                ('training_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainingroom')),
            ],
        ),
    ]
