# Generated by Django 5.0.3 on 2024-03-25 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_trainingroom_lessonschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lesson_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='myapp.lessonschedule'),
            preserve_default=False,
        ),
    ]
