# Generated by Django 5.0.3 on 2024-03-25 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_subscription_lesson_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='day_of_week',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lesson_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='myapp.lessonschedule'),
            preserve_default=False,
        ),
    ]
