# Generated by Django 5.0.3 on 2024-03-25 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_lessonschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='myapp.lessonschedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lesson_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='myapp.lessonschedule'),
            preserve_default=False,
        ),
    ]
